import React from 'react';

import { BOARD_REVIEW_DRAFT_LABELS } from '../utils/reportLabels.js';

export function ReportFooter() {
  return (
    <footer
      className="ceos-report-footer"
      style={{
        marginTop: 28,
        paddingTop: 16,
        borderTop: '1px solid #cbd5e1',
        color: '#475569',
        fontSize: 12,
        lineHeight: 1.6
      }}
    >
      <strong>{BOARD_REVIEW_DRAFT_LABELS.confidential}</strong> - {BOARD_REVIEW_DRAFT_LABELS.status} -{' '}
      {BOARD_REVIEW_DRAFT_LABELS.notLegalAdvice} - {BOARD_REVIEW_DRAFT_LABELS.notInvestmentAdvice} -{' '}
      {BOARD_REVIEW_DRAFT_LABELS.notBoardApproved}. Generated by CEO&apos;s OS. Human review required before circulation.
    </footer>
  );
}

export default ReportFooter;
